-- Migration: 0017_lore_knowledge
-- Expandable offline lore knowledge used by BotChatReactor.

CREATE TABLE IF NOT EXISTS playerbot_v2_lore_topic (
    topic_key VARCHAR(64) NOT NULL PRIMARY KEY,
    aliases TEXT NOT NULL,
    short_answer VARCHAR(500) NOT NULL,
    long_answer TEXT NOT NULL,
    priority SMALLINT NOT NULL DEFAULT 0,
    enabled TINYINT UNSIGNED NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO playerbot_v2_lore_topic
(topic_key, aliases, short_answer, long_answer, priority) VALUES
('azeroth','azeroth|world soul|worldsoul','Azeroth is both the world we defend and the name used for the powerful world-soul sleeping within it.','Azeroth is a world shaped by elemental conflict, Old God corruption, and titan intervention. A powerful world-soul rests within the planet, making Azeroth important to the Titans, the Void, and the Burning Legion.',100),
('titans','titans|pantheon|aman thul|eonar|norgannon|khaz goroth|golganneth|aggramar','The Titans are vast arcane beings who ordered worlds and empowered keepers to protect Azeroth.','The Pantheon includes Aman''Thul, Eonar, Norgannon, Khaz''goroth, Golganneth, and Aggramar. They found Azeroth, fought the Old Gods through titan-forged servants, and left keepers and facilities to guide and defend the world.',90),
('old gods','old gods|black empire|yogg saron|yogg|cthun|c thun|nzoth|n zoth|yshaarj|y shaarj','The Old Gods were Void-born parasites that built the Black Empire and corrupted much of ancient Azeroth.','C''Thun, Yogg-Saron, N''Zoth, and Y''Shaarj were sent by the Void Lords. The Titans'' forces defeated and imprisoned them; Y''Shaarj was torn out, wounding Azeroth and leaving behind the Sha.',95),
('void','void|void lords|shadow','The Void is a cosmic force of possibility, hunger, and madness, opposed most directly by the Light.','Void Lords cannot easily manifest fully in physical reality, so they use agents such as the Old Gods. Void magic reveals countless possible futures, but its whispers can mislead or corrupt those who wield it.',75),
('light','holy light|the light|naaru','The Light is a cosmic force associated with faith, healing, order, and conviction; the naaru are among its great beings.','The Light answers conviction rather than moral alignment alone. Naaru are luminous beings tied to it, although their cycles can carry them into a darkened Void state before renewal.',70),
('burning legion','burning legion|legion|demons','The Burning Legion was Sargeras'' demonic army, created to destroy worlds before the Void could corrupt them.','Sargeras formed the Burning Legion from conquered demons and shattered worlds. It invaded Azeroth repeatedly through agents such as the eredar leaders Kil''jaeden and Archimonde until its campaign was broken at Argus.',95),
('sargeras','sargeras|fallen titan|dark titan','Sargeras is the fallen Titan who created the Burning Legion and sought to destroy Azeroth.','Once the Pantheon''s champion, Sargeras became convinced that annihilation was preferable to a universe ruled by the Void. He created the Burning Legion, manipulated Azeroth''s wars, and was eventually imprisoned with the Pantheon.',95),
('arthas','arthas|lich king|prince arthas|menethil','Arthas Menethil was a paladin prince who took Frostmourne, became a death knight, and ultimately the Lich King.','Trying to save Lordaeron from the plague, Arthas purged Stratholme and pursued Mal''Ganis to Northrend. Frostmourne consumed his soul; he served Ner''zhul, destroyed his kingdom, and later merged with the Lich King before falling at Icecrown.',100),
('frostmourne','frostmourne|runeblade','Frostmourne was the Lich King''s cursed runeblade, able to steal and imprison souls.','Arthas claimed Frostmourne in Northrend despite every warning. The blade took his soul and helped turn him into a death knight. Tirion Fordring shattered it with the Ashbringer during the final battle at Icecrown.',80),
('scourge','scourge|undead scourge|plague of undeath','The Scourge is the undead army created by the Lich King and first unleashed across Lordaeron.','Kil''jaeden transformed Ner''zhul into the first Lich King to prepare Azeroth for the Legion. Through the plague of undeath, necromancers, and death knights, the Scourge devastated Lordaeron and Quel''Thalas.',85),
('illidan','illidan|illidan stormrage|betrayer|demon hunter','Illidan Stormrage is a night elf sorcerer and demon hunter who sacrificed almost everything to oppose the Legion.','Illidan used dangerous arcane and fel power during the War of the Ancients, earning imprisonment and the title Betrayer. He later ruled Outland, trained demon hunters, and helped force the final war against the Legion before becoming Sargeras'' jailer.',100),
('malfurion','malfurion|malfurion stormrage','Malfurion Stormrage is the first mortal druid and one of the greatest defenders of nature and the Emerald Dream.','Taught by Cenarius, Malfurion helped resist the Legion during the War of the Ancients. He became archdruid, husband of Tyrande, and a central protector of the kaldorei, nature, and the Emerald Dream.',70),
('tyrande','tyrande|tyrande whisperwind|night warrior','Tyrande Whisperwind is the high priestess of Elune and a longtime leader of the night elves.','Tyrande fought in the War of the Ancients, freed Illidan when the Legion returned, and led her people beside Malfurion. After Teldrassil burned, she invoked the dangerous power of the Night Warrior to pursue justice.',75),
('sylvanas','sylvanas|sylvanas windrunner|banshee queen','Sylvanas Windrunner was ranger-general of Silvermoon before Arthas raised her as a banshee.','After regaining freedom from the Lich King, Sylvanas founded and ruled the Forsaken. She later became Horde warchief, burned Teldrassil, shattered the Helm of Domination, and faced judgment for the suffering caused by her pact with the Jailer.',100),
('thrall','thrall|goel|go el','Thrall, born Go''el, liberated the orcs, founded the modern Horde, and became a powerful shaman.','Raised as a human gladiator, Thrall escaped, united the orc clans, and led them to Kalimdor. He forged the modern Horde with trolls and tauren, helped defeat the Legion at Hyjal, and later served the world as a shaman.',95),
('jaina','jaina|jaina proudmoore|lady proudmoore','Jaina Proudmoore is a gifted mage, ruler of Kul Tiras, and one of the Alliance''s most influential leaders.','Jaina studied in Dalaran, helped found Theramore, and repeatedly sought peace. The destruction of Theramore hardened her outlook; she later reconciled with Kul Tiras and became its Lord Admiral.',85),
('anduin','anduin|anduin wrynn|king anduin','Anduin Wrynn is the son of Varian, a priestly Alliance leader shaped by compassion and war.','Anduin favored diplomacy but inherited Stormwind''s crown after Varian died. The Jailer forced him to act as a dominated weapon in the Shadowlands, leaving him to struggle with guilt and rediscover his purpose.',80),
('alleria','alleria|alleria windrunner|void elf','Alleria Windrunner is a legendary ranger who learned to wield the Void without surrendering to it.','Alleria fought the Horde in the Second War, traveled beyond the Dark Portal, and spent centuries battling the Legion. Under Locus-Walker she learned to control Void power and later aided the void elves.',75),
('khadgar','khadgar|archmage khadgar','Khadgar is Medivh''s former apprentice and a leading defender of Azeroth against the Horde and Legion.','Khadgar discovered Medivh''s corruption, helped defeat him, and joined the expedition through the Dark Portal. As an archmage of the Kirin Tor, he later united heroes against the Iron Horde and Burning Legion.',75),
('medivh','medivh|guardian of tirisfal','Medivh was the last Guardian of Tirisfal, possessed by Sargeras and used to open the Dark Portal.','Sargeras'' spirit entered Medivh before birth. As Guardian, Medivh contacted Gul''dan and opened the Dark Portal, beginning the First War. After his death and return, he guided the mortal races toward unity at Mount Hyjal.',85),
('horde','horde|the horde|warchief','The modern Horde is an alliance of peoples formed around survival, honor, and mutual defense.','Thrall reshaped the Horde after the demonic corruption of the orcs, allying with the Darkspear trolls and tauren. Forsaken, blood elves, goblins, pandaren, allied races, and others later joined; its history includes both heroic unity and destructive warchiefs.',90),
('alliance','alliance|the alliance|grand alliance','The Alliance is a coalition led historically by human kingdoms and joined by many peoples defending shared ideals and homes.','The modern Alliance grew from the Alliance of Lordaeron formed during the Second War. Humans, dwarves, gnomes, night elves, draenei, worgen, pandaren, and allied races cooperate despite differing cultures and priorities.',90),
('first war','first war|warcraft orcs humans|fall of stormwind','The First War began when the corrupted Horde invaded Azeroth through the Dark Portal and ended with Stormwind''s fall.','Sargeras, acting through Medivh, worked with Gul''dan to open the Dark Portal. The demon-corrupted orcish Horde invaded the kingdom of Stormwind; King Llane was assassinated and the surviving humans fled north.',80),
('second war','second war|tides of darkness','The Second War pitted the old Horde against the Alliance of Lordaeron across the Eastern Kingdoms.','Stormwind''s survivors warned the northern kingdoms, which formed the Alliance of Lordaeron. The Horde advanced under Orgrim Doomhammer but fractured, and the Alliance pushed it back through the Dark Portal.',75),
('third war','third war|reign of chaos|frozen throne','The Third War saw the Scourge destroy Lordaeron and the Legion invade Kalimdor before mortal races united at Mount Hyjal.','The plague turned Lordaeron into the heart of the Scourge, Arthas became a death knight, and Archimonde led the Legion to Kalimdor. Humans, orcs, and night elves united long enough to defeat him at Mount Hyjal.',90),
('war of the ancients','war of the ancients|sundering|great sundering|azshara','The War of the Ancients was the Legion''s first great invasion of Azeroth and ended with the Sundering.','Queen Azshara and the Highborne opened a portal for the Legion through the Well of Eternity. Resistance led by figures including Malfurion, Tyrande, and Illidan stopped Sargeras, but the Well collapsed and shattered ancient Kalimdor.',90),
('dragon aspects','dragon aspects|aspects|alexstrasza|nozdormu|malygos|neltharion|ysera','The Dragon Aspects were empowered to protect life, time, magic, earth, and nature on Azeroth.','Alexstrasza, Nozdormu, Malygos, Neltharion, and Ysera were raised from proto-dragons and empowered by the titan keepers. Betrayal, corruption, and loss fractured their unity, but their flights repeatedly defended Azeroth.',90),
('deathwing','deathwing|neltharion|earth warder|cataclysm','Deathwing was once Neltharion the Earth-Warder before Old God whispers drove him to betrayal and madness.','Neltharion forged the Dragon Soul and turned it against the other flights during the War of the Ancients. As Deathwing he caused the Cataclysm, reshaping Azeroth, before the Aspects and mortal heroes defeated him.',90),
('dragonflight','dragonflight|dragon isles|primal incarnates|fyrakk|razsageth|iridikron','Dragonflight concerns the return of the dragonflights to the Dragon Isles and the conflict with the Primal Incarnates.','The Dragon Isles awakened, calling the flights home. Alexstrasza sought to renew their legacy while Raszageth and the Primalists freed other Incarnates. The conflict explored titan influence, draconic identity, and the restored unity of the Aspects.',75),
('emerald dream','emerald dream|dream|emerald nightmare|nightmare','The Emerald Dream is a vast spirit realm tied to Azeroth''s natural life; corruption transformed parts of it into the Nightmare.','The Dream reflects Azeroth''s untamed natural pattern and is closely tied to druids and the green dragonflight. The Nightmare grew through Old God influence and agents such as Xavius, threatening both the Dream and waking world.',75),
('outland','outland|draenor|dark portal|shattered world','Outland is the shattered remnant of Draenor, homeland of the orcs and refuge of the draenei.','Draenor was damaged by fel corruption and torn apart when Ner''zhul opened many unstable portals. Its surviving fragments became Outland, later contested by the Legion, Illidan, native peoples, and Azeroth''s armies.',80),
('draenei','draenei|eredar|velen|exodar','The draenei are eredar who fled Sargeras with the prophet Velen and followed the Light across the cosmos.','Velen rejected Sargeras while Kil''jaeden and Archimonde accepted demonic power. The exiles became the draenei, settled on Draenor, suffered the orcs'' genocide, and eventually reached Azeroth aboard the Exodar.',80),
('orcs','orcs|orc clans|guldan|gul dan|mannoroth','The orcs are a people of Draenor whose clans were deceived and corrupted into the first Horde.','Kil''jaeden used Gul''dan to manipulate the clans, while Mannoroth''s blood bound many orcs to demonic fury. After wars, internment, and liberation, Thrall led them toward shamanism and a new home in Durotar.',85),
('blood elves','blood elves|sin dorei|quel thalas|sunwell|kael thas','Blood elves are the survivors of Quel''Thalas who took their name after the Scourge destroyed their kingdom and Sunwell.','Prince Kael''thas renamed his people the sin''dorei in memory of their dead. Their struggle with magical withdrawal led through dangerous alliances, while the restored Sunwell eventually became a source of both arcane and holy power.',80),
('night elves','night elves|kaldorei|teldrassil|elune','Night elves are an ancient people shaped by the Well of Eternity, druidism, and devotion to Elune.','After the Sundering, the kaldorei guarded the new Well at Mount Hyjal and lived under Nordrassil''s protection. They later joined the Alliance; the burning of Teldrassil became one of their greatest tragedies.',80),
('forsaken','forsaken|undercity|lordaeron undead','The Forsaken are free-willed undead who broke from the Lich King and built a nation from Lordaeron''s ruins.','Led for years by Sylvanas, the Forsaken joined the Horde out of necessity and shared enemies. Their identity centers on free will, survival, and the complicated legacy of Lordaeron and the Royal Apothecary Society.',75),
('pandaria','pandaria|pandaren|sha|mists of pandaria','Pandaria is an ancient hidden continent where negative emotion could manifest as the Sha.','Emperor Shaohao shrouded Pandaria in mist during the Sundering. Alliance-Horde conflict disturbed the land and empowered the Sha, while Garrosh''s pursuit of power eventually brought war to the Vale of Eternal Blossoms.',75),
('shadowlands','shadowlands|jailer|zovaal|covenants|maw','The Shadowlands are realms of Death where souls were judged and sent to afterlives until the Jailer''s schemes broke the system.','The Arbiter once directed souls among realms such as Bastion, Maldraxxus, Ardenweald, and Revendreth. Zovaal the Jailer exploited the drought of anima and Sylvanas'' actions, but Azeroth''s champions stopped his attempt to remake reality.',80),
('the war within','war within|khaz algar|earthen|xal atath|harbinger','The War Within begins the Worldsoul Saga beneath Azeroth, as heroes journey into Khaz Algar and confront Xal''atath''s plans.','The first chapter of the Worldsoul Saga sends heroes into the subterranean lands of Khaz Algar, home of the Earthen. Xal''atath, the Harbinger, manipulates Void forces while Azeroth''s world-soul calls to key heroes.',95),
('xal atath','xal atath|xalatath|harbinger|black blade','Xal''atath is an ancient Void entity known as the Harbinger, once bound within a blade and now acting through a mortal form.','Xal''atath spent ages imprisoned in the Blade of the Black Empire before securing freedom. She works through prophecy, manipulation, and Void forces, becoming a central threat in the Worldsoul Saga.',90),
('karesh','karesh|k aresh|ethereals|dimensius','K''aresh is the shattered homeworld of the ethereals, devastated by the Void Lord Dimensius.','Dimensius the All-Devouring attacked K''aresh, leaving it fragmented and its people transformed into energy beings known as ethereals. Its surviving eco-domes and ruins remain tied to the Void''s continuing threat.',80),
('worldsoul saga','worldsoul saga|midnight|last titan','The Worldsoul Saga is a three-expansion arc: The War Within, Midnight, and The Last Titan.','The saga centers on Azeroth''s world-soul and escalating cosmic threats. The War Within opens beneath Azeroth, Midnight turns toward a major Void assault, and The Last Titan is planned to confront the legacy and return of the Titans.',95)
ON DUPLICATE KEY UPDATE aliases=VALUES(aliases), short_answer=VALUES(short_answer),
long_answer=VALUES(long_answer), priority=VALUES(priority), enabled=1;

INSERT INTO playerbot_v2_schema_version (version, sha256) VALUES
    (17, REPEAT('0', 64))
ON DUPLICATE KEY UPDATE applied_at = CURRENT_TIMESTAMP;
